name: Execute Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  execute_tests:
    name: Execute tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run - ArchTestsSuiteRunner tests
      run: mvn clean test -am -amd -Dtest=ArchTestsSuiteRunner -Denv=DEV

    - name: Run - FullTestsSuiteRunner tests
      run: mvn clean test -am -amd -Denv=DEV -Dtest=FullTestsSuiteRunner || exit 0

    - name: Export report path
      run: echo "REPORT_FILE=$(ls modules/target/report/)" >> $GITHUB_ENV

    - name: Copy report file
      run: cp ./modules/target/report/${{env.REPORT_FILE}} .

    - uses: actions/upload-artifact@v4
      name: Generate artifact
      with:
        name: ${{env.REPORT_FILE}}
        path: ${{env.REPORT_FILE}}

    - name: Test report
      uses: pavi2410/html-preview-action@v4
      with:
        html_file: ${{env.REPORT_FILE}}
        job_summary: true
